---
- name: "Create Deploy Docker"
  hosts: localhost
  connection: local 
  become: true

  tasks:
  - name: stop current running container
    command: docker stop simple-devops-container
    ignore_errors: yes

  - name: remove stopped container
    command: docker rm simple-devops-container
    ignore_errors: yes

  - name: remove docker image
    command: docker rmi simple-devops-image
    ignore_errors: yes

  - name: build docker image using war
    command: docker build -t simple-devops-image .
    args:
      chdir: /opt/docker
  - name: create container using simple image
    command: docker run -d --name simple-devops-container -p 8080:8080 simple-devops-image
